name: Deploy BiblioTech to GitHub Pages

on:
  # Ejecutar en push a main
  push:
    branches: [ main, master ]
  
  # Permitir ejecuci贸n manual
  workflow_dispatch:

# Permisos necesarios para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Configuraci贸n de concurrencia
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de construcci贸n
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v4
        
      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3
        
      - name: Construir sitio con Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
          
      - name: Subir artefactos para Pages
        uses: actions/upload-pages-artifact@v2

  # Job de despliegue
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2